/**
 * Planning Types for AI-Powered Daily Planner
 *
 * These types support:
 * - Smart daily plan generation
 * - Time tracking and historical learning
 * - Adaptive replanning
 * - Activity templates for recurring tasks
 */

/**
 * Individual time block in a daily plan
 */
export interface TimeBlock {
    id: string;
    planId: string;
    taskId?: string;              // Reference to existing Task from todos
    activityTemplateId?: string;  // Reference to ActivityTemplate
    calendarEventId?: string;     // External calendar event ID
    title: string;
    description?: string;
    startTime: string;            // Time within the day (HH:MM format)
    endTime: string;              // Time within the day (HH:MM format)
    estimatedMinutes: number;     // Original estimate
    actualMinutes?: number;       // Actual time spent (tracked)
    status: 'pending' | 'active' | 'completed' | 'skipped' | 'rescheduled';
    startedAt?: string;           // ISO timestamp when started
    completedAt?: string;         // ISO timestamp when completed
    notes?: string;               // User notes or AI suggestions
    sortOrder: number;            // Order in the day (0-based)
}

/**
 * Complete daily plan generated by AI
 */
export interface DailyPlan {
    id: string;
    userId: string;
    date: string;                 // YYYY-MM-DD format
    blocks: TimeBlock[];

    // Context at plan generation time
    moodAtPlanTime?: number;      // 1-10 scale from tracker
    energyAtPlanTime?: number;    // 1-10 scale from tracker
    sleepHoursAtPlanTime?: number;

    // AI metadata
    aiPromptUsed?: string;        // Prompt template used
    aiModelUsed?: string;         // Model that generated the plan
    aiReasoning?: string;         // AI's explanation of the plan
    aiWarnings?: string[];        // Any warnings (e.g., "Schedule is tight")

    // Plan lifecycle
    createdAt: string;
    updatedAt?: string;
    status: 'draft' | 'active' | 'completed' | 'abandoned';

    // Statistics (computed)
    totalPlannedMinutes?: number;
    totalActualMinutes?: number;
    completionRate?: number;      // Percentage of blocks completed
}

/**
 * Reusable template for standard activities
 * E.g., "Morning routine", "Commute", "Lunch"
 */
export interface ActivityTemplate {
    id: string;
    userId: string;
    name: string;
    emoji?: string;
    description?: string;
    category: 'routine' | 'chore' | 'health' | 'work' | 'leisure' | 'transit' | 'meal' | 'other';

    // Duration estimates
    defaultMinutes: number;       // Default estimate
    historicalMinutes?: number[]; // Last 10-20 actual durations (for learning)
    averageMinutes?: number;      // Computed average from historical data

    // Scheduling preferences
    frequency?: 'daily' | 'weekly' | 'monthly' | 'as-needed';
    preferredTimeSlot?: 'morning' | 'afternoon' | 'evening' | 'any';
    preferredStartTime?: string;  // Specific time preference (HH:MM)

    // Status
    isActive: boolean;            // Whether to include in planning
    createdAt: string;
    updatedAt?: string;
}

/**
 * Calendar event imported from external calendar (iCal/CalDAV)
 */
export interface CalendarEvent {
    id: string;
    userId: string;
    title: string;
    description?: string;
    location?: string;

    // Timing
    startTime: string;            // ISO timestamp
    endTime: string;              // ISO timestamp
    isAllDay: boolean;

    // Travel considerations
    travelTimeMinutes?: number;   // Buffer time before event
    travelFromLocation?: string;

    // Source tracking
    source: 'ical' | 'caldav' | 'manual';
    externalId?: string;          // ID from external calendar
    calendarName?: string;        // Which calendar it came from

    // Metadata
    createdAt: string;
    syncedAt?: string;            // Last sync time
}

/**
 * Context data for AI plan generation
 */
export interface PlanGenerationContext {
    date: string;                 // Date to plan for

    // User state
    mood?: number;
    energy?: number;
    sleepHours?: number;

    // Input data
    tasks: Array<{
        id: string;
        title: string;
        priority: string;
        estimatedTime?: number;
        deadline?: string;
    }>;

    calendarEvents: CalendarEvent[];
    activityTemplates: ActivityTemplate[];

    // Historical context
    previousPlans?: DailyPlan[];  // Recent plans for learning
    taskDurationHistory?: Record<string, number[]>;

    // User preferences
    workStartTime?: string;       // e.g., "09:00"
    workEndTime?: string;         // e.g., "17:00"
    breakPreferences?: {
        includeLunchBreak: boolean;
        lunchDuration?: number;
        includeShortBreaks: boolean;
        shortBreakInterval?: number;
    };
}

/**
 * AI-generated plan suggestion (before user approval)
 */
export interface PlanSuggestion {
    blocks: Omit<TimeBlock, 'id' | 'planId'>[];
    reasoning: string;            // Why the AI structured it this way
    warnings?: string[];          // e.g., "Very tight schedule"
    suggestions?: string[];       // Tips for the user
    totalMinutes: number;
    freeTimeMinutes: number;
}

/**
 * Request to replan remaining tasks
 */
export interface ReplanRequest {
    currentPlanId: string;
    currentTime: string;          // ISO timestamp of "now"
    skipBlockIds?: string[];      // Blocks to skip/remove
    addTasks?: Array<{            // New tasks to add
        id: string;
        title: string;
        estimatedTime: number;
    }>;
    tone?: 'encouraging' | 'neutral';  // Default: encouraging
}

/**
 * Historical tracking for task duration learning
 */
export interface TaskDurationHistory {
    taskId: string;
    taskTitle: string;
    durations: Array<{
        date: string;
        estimatedMinutes: number;
        actualMinutes: number;
        variance: number;         // actual - estimated
    }>;
    averageActual: number;
    averageEstimate: number;
    accuracy: number;             // How close estimates are (percentage)
}

/**
 * Day retrospective data
 */
export interface DayRetrospective {
    planId: string;
    date: string;

    // Completion stats
    blocksPlanned: number;
    blocksCompleted: number;
    blocksSkipped: number;
    completionRate: number;

    // Time stats
    totalPlannedMinutes: number;
    totalActualMinutes: number;
    variance: number;

    // Insights
    mostAccurateEstimates: string[];  // Task titles
    leastAccurateEstimates: string[]; // Task titles
    suggestionsForTomorrow?: string[];

    // Mood at end of day
    endOfDayMood?: number;
    endOfDayEnergy?: number;
}
