/**
 * Task/Todo Converters
 */

import type { Task } from '../../../features/tasks/types';
import type { DbTodo } from '../types';

export function dbToTodo(db: DbTodo): Task {
    return {
        id: db.id,
        title: db.title,
        completed: db.completed,
        dueDate: db.due_date || undefined,
        dueTime: db.due_time || undefined,
        location: db.location || undefined,
        labels: db.labels || undefined,
        createdAt: db.created_at,
        priority: db.priority as Task['priority'],
        estimatedTime: db.estimated_time || undefined,
        subtasks: db.subtasks || [],
        actualMinutes: db.actual_minutes || undefined,
        startedAt: db.started_at || undefined,
        completedAt: db.completed_at || undefined,
        historicalMinutes: db.historical_minutes || undefined,
        recurrence: (db.recurrence as Task['recurrence']) || 'none',
        recurrenceConfig: db.recurrence_config || undefined,
        reminderEnabled: db.reminder_enabled || false,
        reminderOffsetMinutes: db.reminder_offset_minutes ?? undefined,
        reminderAt: db.reminder_at || undefined,
        reminderCadence: (db.reminder_cadence as Task['reminderCadence']) || undefined,
        lastRemindedAt: db.last_reminded_at || undefined,
        taskTypeId: db.task_type_id || undefined,
        assignmentId: db.assignment_id || undefined,
        energy: db.energy || undefined,
        context: db.context || undefined,
        routineId: db.routine_id || undefined,
        routineOrder: db.routine_order ?? undefined,
        kind: (db.kind as Task['kind']) || undefined,
        parentTodoId: db.parent_todo_id || undefined,
        notes: db.notes || undefined,
        triagedAt: db.triaged_at || undefined,
        hardness: (db.hardness as Task['hardness']) || undefined,
        autoTriaged: db.auto_triaged ?? false,
        triageDestination: db.triage_destination || undefined,
        googleEventId: db.google_event_id || undefined,
        googleCalendarId: db.google_calendar_id || undefined,
        googleSyncedAt: db.google_synced_at || undefined,
        snoozeCount: db.snooze_count ?? 0,
        lastTouchedAt: db.last_touched_at || undefined,
    };
}

export function todoToDb(todo: Omit<Task, 'id'> & { id?: string }, userId: string): Omit<DbTodo, 'id' | 'created_at'> & { id?: string; created_at?: string } {
    return {
        id: todo.id,
        user_id: userId,
        title: todo.title,
        completed: todo.completed,
        due_date: todo.dueDate || null,
        due_time: todo.dueTime || null,
        location: todo.location || null,
        labels: todo.labels || null,
        created_at: todo.createdAt,
        priority: todo.priority || null,
        estimated_time: todo.estimatedTime || null,
        subtasks: todo.subtasks || null,
        actual_minutes: todo.actualMinutes || null,
        started_at: todo.startedAt || null,
        completed_at: todo.completedAt || null,
        historical_minutes: todo.historicalMinutes || null,
        recurrence: todo.recurrence || 'none',
        recurrence_config: todo.recurrenceConfig || null,
        reminder_enabled: todo.reminderEnabled || false,
        reminder_offset_minutes: todo.reminderOffsetMinutes ?? null,
        reminder_at: todo.reminderAt || null,
        reminder_cadence: todo.reminderCadence || null,
        last_reminded_at: todo.lastRemindedAt || null,
        task_type_id: todo.taskTypeId || null,
        assignment_id: todo.assignmentId || null,
        energy: todo.energy || null,
        context: todo.context || null,
        routine_id: todo.routineId || null,
        routine_order: todo.routineOrder ?? null,
        // 'school' is a derived-only kind — the DB CHECK doesn't allow it.
        kind: todo.kind === 'school' ? null : todo.kind || null,
        parent_todo_id: todo.parentTodoId || null,
        notes: todo.notes || null,
        triaged_at: todo.triagedAt || null,
        hardness: todo.hardness || null,
        auto_triaged: todo.autoTriaged ?? false,
        triage_destination: todo.triageDestination || null,
        google_event_id: todo.googleEventId || null,
        google_calendar_id: todo.googleCalendarId || null,
        google_synced_at: todo.googleSyncedAt || null,
        snooze_count: todo.snoozeCount ?? 0,
        last_touched_at: todo.lastTouchedAt || null,
    };
}
