-- Assistant Rules: dynamic routing rules generated by the Trainer agent
-- These are loaded by the General Manager at runtime to supplement built-in rules

CREATE TABLE IF NOT EXISTS assistant_rules (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  domain TEXT NOT NULL,
  pattern TEXT NOT NULL,                  -- regex pattern string
  action TEXT NOT NULL,                   -- the intent/action to route to
  confidence REAL NOT NULL DEFAULT 0.8,   -- how confident the trainer is (0-1)
  source TEXT NOT NULL DEFAULT 'trainer' CHECK (source IN ('manual', 'trainer', 'builtin')),
  active BOOLEAN NOT NULL DEFAULT true,
  finding_id UUID REFERENCES assistant_findings(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_assistant_rules_user_id ON assistant_rules(user_id);
CREATE INDEX IF NOT EXISTS idx_assistant_rules_active ON assistant_rules(user_id, active);
CREATE INDEX IF NOT EXISTS idx_assistant_rules_domain ON assistant_rules(domain);

-- Row Level Security
ALTER TABLE assistant_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own rules"
  ON assistant_rules FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can manage own rules"
  ON assistant_rules FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Service role can manage rules (Trainer agent uses service key)
CREATE POLICY "Service can manage rules"
  ON assistant_rules FOR ALL
  USING (true)
  WITH CHECK (true);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_assistant_rules_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER assistant_rules_updated_at
  BEFORE UPDATE ON assistant_rules
  FOR EACH ROW EXECUTE FUNCTION update_assistant_rules_updated_at();
